### ISSUE TITLE
SphinX Build Hatası

### ISSUE THREAD

**Issue by woosal1337** [yazbel/python-istihza#178]
[CONTRIBUTING.md](https://github.com/yazbel/python-istihza/blob/master/CONTRIBUTING.md) dosyasında Sphinx kullanımı için  Linux üzerinde `apt` kullanarak kurulması önerilmişti. Bunu ilk denememde herşeyin kurulumunu (requirement kütüphaneleri de kurduktan sonra) yapmama rağmen build kısmında yine de sıkıntılar çıkarıyordu.

Bu yüzden [Sphinx Websitesi](https://www.sphinx-doc.org/en/master/) üzerinden `pip` kullanarak indirdiğim versiyonu denedim. Onda bir sıkıntı çıkmıyordu. Sphinx kurulumunun [CONTRIBUTING.md](https://github.com/yazbel/python-istihza/blob/master/CONTRIBUTING.md) dosyasına `pip` kullanarak da eklemek sizce `apt` kullanarak çalışdıramayanlar için bir seçim olarak eklesek yararlı olmaz mı?

**Comment by ismailarilik** [comment]
Bence iyi olur.

26 Eyl 2021 Paz 16:59 tarihinde Vusal Ismayilov ***@***.***>
şunu yazdı:

**Comment by woosal1337** [comment]
O zaman CONTRIBUTION icin o eklemeyi yapiyorum.
