### ISSUE TITLE
html sayfalarını ana dizine kopyalama betiği hatası

### ISSUE THREAD

**Issue by kaleturgay** [yazbel/python-istihza#184]
Windows host bilgisayara, kaynak dosyaları ilk defa indirip çalıştırdım. move.py de aşağıdaki gibi hata aldım.
Hatanın sebebi host ta python 2.x in de kurulu olması ve python <dosya.py> çağrılarında python 2.x nin çağrılmasıymış. 
python 3.x ile çalıştırmak gerekiyor.

_C:\Users\xxx\Documents\python3-turkce-git\python-istihza>python move.py
  File "move.py", line 17
    print(f"INFO: Adding the new file {repr(i)} to the project.")
                                                               ^
SyntaxError: invalid syntax_

**Comment by kaleturgay** [comment]
"python" yerine "py -3" ifadesi kullanılabilir. Bu tüm sistemlerde çalışacaktır diye düşünüyorum.

**Comment by BatuAkkurtt** [comment]
python3 veya py3 ile çalışacaktır.

**Comment by ismailarilik** [comment]
Windows'ta `py -3` komutu, Mac OS ve GNU/Linux'te ise `python3` komutunu kullanmalısınız.
