### ISSUE TITLE
Bölüm 14.04.02 ve Bölüm 32.03

### ISSUE THREAD

**Issue by ghost** [yazbel/python-istihza#186]
Bölüm 14.04.02'de "Dosyaların İçeriğini Karşılaştırma" konusunda şu cümle yer alıyor "Burada bir öncekinden farklı olarak if not i in d2_satırlar kodu yerine, doğal olarak, if i in d2_satırlar kodunu kullandığımıza dikkat edin."

Bu cümle, "Karakter Dizisindeki Karakterleri Sayma" başlığının biraz üstünde yer alıyor. Bu cümlede d2 ifadeleri d1 olmalı. "not in" yerine "in" yazılan satırda if i in d1_satırlar yazıyor, yani d2 yok, d1 var.

Bölüm 32.03'te "Sözlüklerin öteki veri tiplerinden önemli bir farkı, sözlük içinde yer alan öğelerin herhangi bir sıralama mantığına sahip olmamasıdır. Yani sözlükteki öğeler açısından ‘sıra’ diye bir kavram yoktur." yazmaktadır. Ancak Python'ın son sürümlerinde sözlüklere sıralama getirilmiştir.

Bilginize sunarım.

**Comment by masanbasa3k** [comment]
Hatayı düzeltip pull request olarak gönderdim onaylandığı zaman düzelecektir.

**Comment by EkremDincel** [comment]
Fixed by #219
