### ISSUE TITLE
Sayfa 1200 import tekrarı

### ISSUE THREAD

**Issue by Aruzz** [yazbel/python-istihza#200]
import tekrarı var.
![image](https://user-images.githubusercontent.com/22779094/192701041-5554c8a7-0406-4136-a574-02814d0a6c26.png)

**Comment by masanbasa3k** [comment]
Hatayı düzeltip pull request olarak gönderdim onaylandığı zaman düzelecektir.

**Comment by EkremDincel** [comment]
Fixed by #216
