### ISSUE TITLE
Yazım hatası.. "görüntülecektir" yazılmış..

### ISSUE THREAD

**Issue by Natuvan** [yazbel/python-istihza#208]
https://python-istihza.yazbel.com/islecler.html
"görüntülecektir" yazılmış
"görüntülenecektir" olacak...

**Comment by Natuvan** [comment]
https://python-istihza.yazbel.com/islecler.html
"görüntülecektir" yazılmış
"görüntülenecektir" olacak...

**Comment by masanbasa3k** [comment]
Hatayı düzeltip pull request olarak gönderdim onaylandığı zaman düzelecektir.

**Comment by EkremDincel** [comment]
Fixed by #216
