### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by AhmetCK3319** [yazbel/python-istihza#210]
giriş = input("Merhaba! Adın ne? ")
assert len(giriş) != 0 , "İsim bölümü boş."
print("Hoşgeldiniz.")

belki daha önce söylenmiştir ancak != ifadesi == ifadesi olmalıydı sanırım teşekkürler

**Comment by masanbasa3k** [comment]
Yazdığınız kod bloğunun altında böyle bir paragraf bulunmakta.
![image](https://github.com/yazbel/python-istihza/assets/66223190/75900d0d-9463-435b-8f08-77673cbb9dbb)
Yani anlayacağınız assert kullanımı bu şekilde çalışmaktadır kodda herhangi bir hata yoktur

**Comment by EkremDincel** [comment]
@masanbasa3k nın da dediği gibi kod doğru.

**Comment by ismailarilik** [comment]
Temizlik için teşekkürler. =)
