### ISSUE TITLE
casefold() metodundaki hatalı açıklama

### ISSUE THREAD

**Issue by ghost** [yazbel/python-istihza#211]
Karakter dizileri metotlarından casefold() metodunda Türkçe karakterlerin küçük harfe doğru dönüştürülemediği yazılmış. Ama ben doğru çalıştığını test ettim. Büyük İ harfi başarıyla küçük i ye dönüştürülüyor. Test ettiğim Python sürümü : 3.9.7

**Comment by masanbasa3k** [comment]
"Türkçedeki İ-i sorunu bu metot için de aynen geçerlidir." Şeklinde bir cümle var evet dediğiniz gibi. Çok büyük ihtimalle sürüm farkından kaynaklı bir sorun.
Şu linke bakarsanız bir şeyler bulabileceğinizi umuyorum. Zaten başlığı açan kişi Fırat Özgül.
https://bugs.python.org/issue17252

**Comment by EkremDincel** [comment]
Problem devam ediyor. İ'nin i'ye dönüştürülmemesi değildi zaten problem (Python 3.9.13):

```python
>>> "I".lower()
'i'
>>> "I".casefold()
'i'
>>> "i".upper()
'I'
>>> "i".casefold()
'i'
```
