### ISSUE TITLE
Bölüm 39 - 09 Örnek Metodları - sanırım çıktıda bir hata var.

### ISSUE THREAD

**Issue by takicak** [yazbel/python-istihza#212]
https://python-istihza.yazbel.com/nesne_tabanli_programlama1.html#ornek-metotlari
sitesinde 

--------------------------------------------------------------------------------------
Böylece ilk çalışanın ismini ‘Mahmut’ olarak değiştirdik:
ç1.isim
'Mahmut'

ç1.personel
['Mahmut', 'Mehmet']   **<-- Bu çıktının hatalı olabileceği kanısındayım.**
--------------------------------------------------------------------------------------------

Site güncellenmemiş, github kısmı daha güncel olabilir bilemiyorum.
Github içinde bahsettiğim dökümanı tam olarak bulamadım.

Gözden geçirebilecek arkadaşlara şimdiden teşekkürler.

**Comment by ozgurturkiye** [comment]
Belgedeki anlatım doğru gözüküyor benim görebildiğim bir hata yok. Bölümü sonuna kadar okursanız neden böyle olduğunu anlatmış. Sayfada alttaki cümlenin geçtiği paragrafı okursanız anlayacaksınız.

> Hele bir de bu sınıf niteliği, listeler gibi değiştirilebilir (mutable) bir veri tipi ise, bu durum hiç de istemediğiniz sonuçlar doğurabilir.

Github üzerinde .rst uzantılı kaynak dosyasına ulaşmak için: https://github.com/yazbel/python-istihza/blob/master/source/nesne_tabanli_programlama1.rst

**Comment by EkremDincel** [comment]
Kodu çalıştırırsanız dökümanın yanlış olmadığını görebilirsiniz.
